#url: https://y7kim.github.io
#baseurl: /agency-jekyll-theme/

url:
baseurl:

# Site settings
title: LBK
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Livereload
livereload: true

# Build settings
markdown: kramdown
permalink: pretty