#url: https://y7kim.github.io

#url: http://www.lbkadvertising.com

url:
baseurl:

# Site settings
title: LBK
email: joe@lbkadvertising.com
description: "LBK advertising. We’re a digital ad agency that specializes in increasing brand awareness, sales, and store visits through highly targeted digital ad campaigns."

# Livereload
livereload: true

# Build settings
markdown: kramdown
permalink: pretty
